Update Node.js to current LTS version 20
react-native-community/docker-android pull request #220
Opened 2024-05-02 09:39 UTC by sturman

2024-05-02 12:52 UTC, cortinico requested changes
This will have to follow the same version we use inside react-native. Can't be merged till we bump RN to Node 20

2024-11-03 22:58 UTC, bitcrumb commented
@cortinico Any update on this?

2025-02-25 11:09 UTC, cortinico approved these changes

2025-02-25 11:09 UTC, cortinico commented on Dockerfile
> +ARG NODE_VERSION=20
```suggestion
ARG NODE_VERSION=20.18
```

2025-02-25 11:10 UTC, cortinico commented
We're moving this forward as we're migrating also `react-native` to Node 20 in the coming days 👍

2025-02-25 11:51 UTC, merged